### YamlMime:ManagedReference
items:
- uid: Virtufin.WorkManager.Configuration.DaprConstants
  commentId: T:Virtufin.WorkManager.Configuration.DaprConstants
  id: DaprConstants
  parent: Virtufin.WorkManager.Configuration
  children:
  - Virtufin.WorkManager.Configuration.DaprConstants.PubsubName
  - Virtufin.WorkManager.Configuration.DaprConstants.PubsubNameKey
  - Virtufin.WorkManager.Configuration.DaprConstants.StateStoreName
  - Virtufin.WorkManager.Configuration.DaprConstants.StateStoreNameKey
  langs:
  - csharp
  - vb
  name: DaprConstants
  nameWithType: DaprConstants
  fullName: Virtufin.WorkManager.Configuration.DaprConstants
  type: Class
  source:
    remote:
      path: src/Virtufin.WorkManager/Configuration/DaprConstants.cs
      branch: master
      repo: https://git.haenerconsulting.com/virtufin/virtufin-workmanager
    id: DaprConstants
    path: ../../../src/Virtufin.WorkManager/Configuration/DaprConstants.cs
    startLine: 2
  assemblies:
  - Virtufin.WorkManager
  namespace: Virtufin.WorkManager.Configuration
  syntax:
    content: public static class DaprConstants
    content.vb: Public Module DaprConstants
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Virtufin.WorkManager.Configuration.DaprConstants.PubsubName
  commentId: F:Virtufin.WorkManager.Configuration.DaprConstants.PubsubName
  id: PubsubName
  parent: Virtufin.WorkManager.Configuration.DaprConstants
  langs:
  - csharp
  - vb
  name: PubsubName
  nameWithType: DaprConstants.PubsubName
  fullName: Virtufin.WorkManager.Configuration.DaprConstants.PubsubName
  type: Field
  source:
    remote:
      path: src/Virtufin.WorkManager/Configuration/DaprConstants.cs
      branch: master
      repo: https://git.haenerconsulting.com/virtufin/virtufin-workmanager
    id: PubsubName
    path: ../../../src/Virtufin.WorkManager/Configuration/DaprConstants.cs
    startLine: 4
  assemblies:
  - Virtufin.WorkManager
  namespace: Virtufin.WorkManager.Configuration
  syntax:
    content: public const string PubsubName = "pubsub"
    return:
      type: System.String
    content.vb: Public Const PubsubName As String = "pubsub"
- uid: Virtufin.WorkManager.Configuration.DaprConstants.StateStoreName
  commentId: F:Virtufin.WorkManager.Configuration.DaprConstants.StateStoreName
  id: StateStoreName
  parent: Virtufin.WorkManager.Configuration.DaprConstants
  langs:
  - csharp
  - vb
  name: StateStoreName
  nameWithType: DaprConstants.StateStoreName
  fullName: Virtufin.WorkManager.Configuration.DaprConstants.StateStoreName
  type: Field
  source:
    remote:
      path: src/Virtufin.WorkManager/Configuration/DaprConstants.cs
      branch: master
      repo: https://git.haenerconsulting.com/virtufin/virtufin-workmanager
    id: StateStoreName
    path: ../../../src/Virtufin.WorkManager/Configuration/DaprConstants.cs
    startLine: 5
  assemblies:
  - Virtufin.WorkManager
  namespace: Virtufin.WorkManager.Configuration
  syntax:
    content: public const string StateStoreName = "statestore"
    return:
      type: System.String
    content.vb: Public Const StateStoreName As String = "statestore"
- uid: Virtufin.WorkManager.Configuration.DaprConstants.PubsubNameKey
  commentId: F:Virtufin.WorkManager.Configuration.DaprConstants.PubsubNameKey
  id: PubsubNameKey
  parent: Virtufin.WorkManager.Configuration.DaprConstants
  langs:
  - csharp
  - vb
  name: PubsubNameKey
  nameWithType: DaprConstants.PubsubNameKey
  fullName: Virtufin.WorkManager.Configuration.DaprConstants.PubsubNameKey
  type: Field
  source:
    remote:
      path: src/Virtufin.WorkManager/Configuration/DaprConstants.cs
      branch: master
      repo: https://git.haenerconsulting.com/virtufin/virtufin-workmanager
    id: PubsubNameKey
    path: ../../../src/Virtufin.WorkManager/Configuration/DaprConstants.cs
    startLine: 6
  assemblies:
  - Virtufin.WorkManager
  namespace: Virtufin.WorkManager.Configuration
  syntax:
    content: public const string PubsubNameKey = "pubsubName"
    return:
      type: System.String
    content.vb: Public Const PubsubNameKey As String = "pubsubName"
- uid: Virtufin.WorkManager.Configuration.DaprConstants.StateStoreNameKey
  commentId: F:Virtufin.WorkManager.Configuration.DaprConstants.StateStoreNameKey
  id: StateStoreNameKey
  parent: Virtufin.WorkManager.Configuration.DaprConstants
  langs:
  - csharp
  - vb
  name: StateStoreNameKey
  nameWithType: DaprConstants.StateStoreNameKey
  fullName: Virtufin.WorkManager.Configuration.DaprConstants.StateStoreNameKey
  type: Field
  source:
    remote:
      path: src/Virtufin.WorkManager/Configuration/DaprConstants.cs
      branch: master
      repo: https://git.haenerconsulting.com/virtufin/virtufin-workmanager
    id: StateStoreNameKey
    path: ../../../src/Virtufin.WorkManager/Configuration/DaprConstants.cs
    startLine: 7
  assemblies:
  - Virtufin.WorkManager
  namespace: Virtufin.WorkManager.Configuration
  syntax:
    content: public const string StateStoreNameKey = "stateStoreName"
    return:
      type: System.String
    content.vb: Public Const StateStoreNameKey As String = "stateStoreName"
references:
- uid: Virtufin.WorkManager.Configuration
  commentId: N:Virtufin.WorkManager.Configuration
  href: Virtufin.html
  name: Virtufin.WorkManager.Configuration
  nameWithType: Virtufin.WorkManager.Configuration
  fullName: Virtufin.WorkManager.Configuration
  spec.csharp:
  - uid: Virtufin
    name: Virtufin
    href: Virtufin.html
  - name: .
  - uid: Virtufin.WorkManager
    name: WorkManager
    href: Virtufin.WorkManager.html
  - name: .
  - uid: Virtufin.WorkManager.Configuration
    name: Configuration
    href: Virtufin.WorkManager.Configuration.html
  spec.vb:
  - uid: Virtufin
    name: Virtufin
    href: Virtufin.html
  - name: .
  - uid: Virtufin.WorkManager
    name: WorkManager
    href: Virtufin.WorkManager.html
  - name: .
  - uid: Virtufin.WorkManager.Configuration
    name: Configuration
    href: Virtufin.WorkManager.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
