### YamlMime:ManagedReference
items:
- uid: Virtufin.WorkManager.Configuration
  commentId: N:Virtufin.WorkManager.Configuration
  id: Configuration
  parent: Virtufin.WorkManager
  children:
  - Virtufin.WorkManager.Configuration.DaprConstants
  - Virtufin.WorkManager.Configuration.DaprResilienceOptions
  - Virtufin.WorkManager.Configuration.InfraEvents
  - Virtufin.WorkManager.Configuration.PortConstants
  - Virtufin.WorkManager.Configuration.Topics
  - Virtufin.WorkManager.Configuration.WorkerEvents
  - Virtufin.WorkManager.Configuration.WorkerProcessingRetryOptions
  - Virtufin.WorkManager.Configuration.WorkerRecoveryOptions
  langs:
  - csharp
  - vb
  name: Virtufin.WorkManager.Configuration
  nameWithType: Virtufin.WorkManager.Configuration
  fullName: Virtufin.WorkManager.Configuration
  type: Namespace
  assemblies:
  - Virtufin.WorkManager
references:
- uid: Virtufin.WorkManager.Configuration.DaprConstants
  commentId: T:Virtufin.WorkManager.Configuration.DaprConstants
  href: Virtufin.WorkManager.Configuration.DaprConstants.html
  name: DaprConstants
  nameWithType: DaprConstants
  fullName: Virtufin.WorkManager.Configuration.DaprConstants
- uid: Virtufin.WorkManager.Configuration.DaprResilienceOptions
  commentId: T:Virtufin.WorkManager.Configuration.DaprResilienceOptions
  parent: Virtufin.WorkManager.Configuration
  href: Virtufin.WorkManager.Configuration.DaprResilienceOptions.html
  name: DaprResilienceOptions
  nameWithType: DaprResilienceOptions
  fullName: Virtufin.WorkManager.Configuration.DaprResilienceOptions
- uid: Virtufin.WorkManager.Configuration.InfraEvents
  commentId: T:Virtufin.WorkManager.Configuration.InfraEvents
  href: Virtufin.WorkManager.Configuration.InfraEvents.html
  name: InfraEvents
  nameWithType: InfraEvents
  fullName: Virtufin.WorkManager.Configuration.InfraEvents
- uid: Virtufin.WorkManager.Configuration.PortConstants
  commentId: T:Virtufin.WorkManager.Configuration.PortConstants
  href: Virtufin.WorkManager.Configuration.PortConstants.html
  name: PortConstants
  nameWithType: PortConstants
  fullName: Virtufin.WorkManager.Configuration.PortConstants
- uid: Virtufin.WorkManager.Configuration.Topics
  commentId: T:Virtufin.WorkManager.Configuration.Topics
  href: Virtufin.WorkManager.Configuration.Topics.html
  name: Topics
  nameWithType: Topics
  fullName: Virtufin.WorkManager.Configuration.Topics
- uid: Virtufin.WorkManager.Configuration.WorkerEvents
  commentId: T:Virtufin.WorkManager.Configuration.WorkerEvents
  href: Virtufin.WorkManager.Configuration.WorkerEvents.html
  name: WorkerEvents
  nameWithType: WorkerEvents
  fullName: Virtufin.WorkManager.Configuration.WorkerEvents
- uid: Virtufin.WorkManager.Configuration.WorkerProcessingRetryOptions
  commentId: T:Virtufin.WorkManager.Configuration.WorkerProcessingRetryOptions
  parent: Virtufin.WorkManager.Configuration
  href: Virtufin.WorkManager.Configuration.WorkerProcessingRetryOptions.html
  name: WorkerProcessingRetryOptions
  nameWithType: WorkerProcessingRetryOptions
  fullName: Virtufin.WorkManager.Configuration.WorkerProcessingRetryOptions
- uid: Virtufin.WorkManager.Configuration.WorkerRecoveryOptions
  commentId: T:Virtufin.WorkManager.Configuration.WorkerRecoveryOptions
  parent: Virtufin.WorkManager.Configuration
  href: Virtufin.WorkManager.Configuration.WorkerRecoveryOptions.html
  name: WorkerRecoveryOptions
  nameWithType: WorkerRecoveryOptions
  fullName: Virtufin.WorkManager.Configuration.WorkerRecoveryOptions
- uid: Virtufin.WorkManager.Configuration
  commentId: N:Virtufin.WorkManager.Configuration
  href: Virtufin.html
  name: Virtufin.WorkManager.Configuration
  nameWithType: Virtufin.WorkManager.Configuration
  fullName: Virtufin.WorkManager.Configuration
  spec.csharp:
  - uid: Virtufin
    name: Virtufin
    href: Virtufin.html
  - name: .
  - uid: Virtufin.WorkManager
    name: WorkManager
    href: Virtufin.WorkManager.html
  - name: .
  - uid: Virtufin.WorkManager.Configuration
    name: Configuration
    href: Virtufin.WorkManager.Configuration.html
  spec.vb:
  - uid: Virtufin
    name: Virtufin
    href: Virtufin.html
  - name: .
  - uid: Virtufin.WorkManager
    name: WorkManager
    href: Virtufin.WorkManager.html
  - name: .
  - uid: Virtufin.WorkManager.Configuration
    name: Configuration
    href: Virtufin.WorkManager.Configuration.html
